update actions

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -233,7 +233,12 @@ jobs:
           git config user.email 41898282+github-actions[bot]@users.noreply.github.com
           git add ..
           git commit -a -m "sdk: release v$VERSION"
-          git push origin HEAD
+          git pull --rebase origin master
+          git push origin HEAD || {
+            echo "Push failed. Retrying after pulling latest changes..."
+            git pull --rebase origin master
+            git push origin HEAD
+          }
       - name: Publish to npm
         run: npm publish --access=public
         env:
